version: "3"
services:
  nodemonitor:
    build: .
    image: fredi/ubix-node-monitor
    container_name: ubix-node-monitor
    volumes:
      - ../config:/var/app/config
    environment:
      # SPRING_PROFILES_ACTIVE: set 'log-fluentd' to send logs to local fluentd, 'default' otherwise. NOT TESTED YET
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_LOCATION: /var/app/config/application.properties
